import React from "react";
import FormInputItem from "./FormInputItem";
import FormDatePickerItem from "./FormDatePickerItem";
import dayjs from "dayjs";

const DesignationContainer = ({
  formType,
  genByVisible,
  genName,
  genDate,
  handleChange,
  issueVisible,
  issueName,
  issueDate,
  approvedVisible,
  processType,
  readOnly
}) => {
  return (
    <div className="designations-container">
      {genByVisible && (
        <div className="each-desg">
          <h4> Generated By </h4>
          <FormInputItem
            placeholder="Name and Designation"
            name="genName"
            readOnly={readOnly}
          />
          <FormDatePickerItem
            name="genDate"
            onChange={handleChange}
            value={genDate}
            readOnly={readOnly}
          />
        </div>
      )}

      {approvedVisible && (
        <div className="each-desg">
          <h4>Approved By</h4>
          <FormInputItem
            placeholder="Name and Signature"
            name="approvedName"
            onChange={handleChange}
            readOnly={readOnly}
          />

          <FormDatePickerItem
            defaultValue={dayjs()}
            name="approvedDate"
            onChange={handleChange}
            readOnly={readOnly}
          />
        </div>
      )}

      {issueVisible && formType !== "PO" && (
        <div className="each-desg">
          <h4>
            {processType === "IRP" ||
            processType === "NIRP" ||
            processType === "IOP"
              ? "Received By"
              : "Verified By"}{" "}
          </h4>
          <FormInputItem
            placeholder="Name and Signature"
            name="issueName"
            value={issueName}
            onChange={handleChange}
            readOnly={readOnly}
          />

          <FormDatePickerItem
            defaultValue={dayjs()}
            name="issueDate"
            onChange={handleChange}
            value={issueDate}
            readOnly={readOnly}
          />
        </div>
      )}
    </div>
  );
};

export default DesignationContainer;
