import React from 'react'
import FormInputItem from './FormInputItem'
import FormDatePickerItem from './FormDatePickerItem'
import dayjs from "dayjs";

const DesignationContainer = ({formType, genByVisible, genName, genDate, handleChange, issueVisible, issueName, issueDate}) => {
  return (
    <div className='designations-container'>
      {
        genByVisible && 
        <div className="each-desg">
        <h4> Generated By </h4>
        <FormInputItem
          placeholder="Name and Designation"
          name="genName"
          // value={genName}
        />
          <FormDatePickerItem
            defaultValue={dayjs()}
            name="genDate"
            onChange={handleChange}
            value={genDate}
          />
        
      </div>
      }

      {
        issueVisible && formType !== 'PO' && 
        <div className="each-desg">
        <h4>
          {formType === "PO" ? "Received By" : "Verified By"}{" "}
        </h4>
        <FormInputItem
          placeholder="Name and Signature"
          name="issueName"
          value={issueName}
          onChange={handleChange}
        />

          <FormDatePickerItem
            defaultValue={dayjs()}
            name="issueDate"
            onChange={handleChange}
            value={issueDate}
          />
      </div>
      }
    </div>
  )
}

export default DesignationContainer
