import React from 'react'

const AcceptanceNoteTable = () => {

    const actTableColumns = [
        {
            title: "Generated Date",
            dataIndex: "genDate"
        },
        {
            title: "Generated By",
            dataIndex: "genName"
        },
        {
            title: "Approval Date",
            dataIndex: "approvedDate"
        },
        {
            title: "Approval Name",
            dataIndex: "approvedName"
        },
        {
            title: "Detail ID",
            dataIndex: "id"
        },
        {
            title: "Process ID",
            dataIndex: "processId"
        },
        {
            title: "Process Type",
            dataIndex: "type"
        },
        {
            title: "Note Type",
            dataIndex: "typeOfNote"
        },
        {
            title: "Inspection Report No.",
            dataIndex: "inspectionRptNo"
        },
        {
            title: "Acceptance Note No.",
            dataIndex: "acptRejNoteNo"
        },
        {
            title: "Acceptance Note Date",
            dataIndex: "acptRejNoteDT"
        },
        {
            title: "Consignee Regional Center Code",
            dataIndex: "ceRegionalCenterCd"
        },
        {
            title: "Consignee Regional Center Name",
            dataIndex: "ceRegionalCenterName"
        },
        {
            title: "Consignee Address",
            dataIndex: "ceAddress"
        },
        {
            title: "Consignee Zipcode",
            dataIndex: "ceZipcode"
        },
        {
            title: "Consignor Regional Center Code",
            dataIndex: "crRegionalCenterCd"
        },
        {
            title: "Consignor Regional Center Name",
            dataIndex: "crRegionalCenterName"
        },
        {
            title: "Consignor Address",
            dataIndex: "crAddress"
        },
        {
            title: "Consignor Zipcode",
            dataIndex: "crZipcode"
        },
    ]

  return (
    <div>
      
    </div>
  )
}

export default AcceptanceNoteTable
