import React, { useEffect, useState } from 'react'
// import { itemDetails, orgConsigneeDetails, orgConsignorDetails, supplierDetails } from './../CommonColumns'
import { apiHeader, convertArrayToObject, convertEpochToDateString } from '../../../utils/Functions'
import DetailData from './DetailData'
import axios from 'axios'

const AcceptanceNoteTable = ({type, data, itemList}) => {
    const token = localStorage.getItem("token")
    const [uomObj, setUomObj] = useState({})

    const fetchUom = async () => {
        // console.log("Fetch uom called")
        const uomMasterUrl =
            "https://uat-sai-app.azurewebsites.net/sai-inv-mgmt/master/getUOMMaster";
    
        try{
            const {data} = await axios.get(uomMasterUrl, apiHeader("GET", token))
            const {responseData} = data
            // console.log("Response data: ", responseData)
            
            const uomMod =  convertArrayToObject(responseData, "id", "uomName")

            setUomObj({...uomMod})
    
        }
        catch(error){
            console.log("Error")
        }
    }

    useEffect(()=>{
        fetchUom()
    }, [])
    const orgConsignorDetails = [
        {
            title: "Consignor Regional Center Code",
            dataIndex: "crRegionalCenterCd"
        },
        {
            title: "Consignor Regional Center Name",
            dataIndex: "crRegionalCenterName"
        },
        {
            title: "Consignor Address",
            dataIndex: "crAddress"
        },
        {
            title: "Consignor Zipcode",
            dataIndex: "crZipcode"
        }
    ]
    const orgConsigneeDetails = [
        {
            title: "Consignee Regional Center Code",
            dataIndex: "ceRegionalCenterCd"
        },
        {
            title: "Consignee Regional Center Name",
            dataIndex: "ceRegionalCenterName"
        },
        {
            title: "Consignee Address",
            dataIndex: "ceAddress"
        },
        {
            title: "Consignee Zipcode",
            dataIndex: "ceZipcode"
        }
    ]
    
    const consumerDetails = [
        {
            title: "Consumer Name",
            dataIndex: "consumerName"
        },
        {
            title: "Contact No.",
            dataIndex: "contactNo"
        }
    ]
    
    const itemDetails = [
        {
            title: "Item Code",
            dataIndex: "itemCode"
        },
        {
            title: "Item Description",
            dataIndex: "itemDesc"
        },
        {
            title: "Uom Description",
            dataIndex: "uom",
            render: (uom) => uomObj[parseInt(uom)]
        },
    ]  
    
    const supplierDetails = [
        {
            title: "Supplier Code",
            dataIndex: "supplierCd" || "supplierCode"
        },
        {
            title: "Supplier Name",
            dataIndex: "supplierName"
        },
        {
            title: "Supplier Address",
            dataIndex: "crAddress"
        }
    ]
    const actDataTableColumns = [
        {
            title: "Acceptance Note No.",
            dataIndex: "processId"
        },
        {
            title: "Acceptance Note Date",
            dataIndex: "acptRejNoteDT"
        },
        {
            title: "Process Type",
            dataIndex: "type"
        },
        {
            title: "Generated Date",
            dataIndex: "genDate"
        },
        {
            title: "Generated By",
            dataIndex: "genName"
        },
        {
            title: "Process ID",
            dataIndex: "processId"
        },
        ...orgConsigneeDetails,

        {
            title: "Noa No.",
            dataIndex: "noa"
        },
        {
            title: "Noa Date",
            dataIndex: "noaDate",
            render: (date) => convertEpochToDateString(date)
        },
        {
            title: "Date of Delivery",
            dataIndex: "dateOfDelivery"
        },
    ]

    const actItemTableColumn = [
        ...itemDetails,
        {
            title: "Accepted Quantity",
            dataIndex: "acceptedQuantity"
        },
        {
            title: "Remarks",
            dataIndex: "remarks"
        }
    ]

  return (
    <DetailData dataColumn={type === "PO" ? [...actDataTableColumns, ...supplierDetails] : [...actDataTableColumns, ...orgConsignorDetails]} itemListColumn={actItemTableColumn} data={data} itemList={itemList}/>
  )
}

export default AcceptanceNoteTable
