export const columnName = {
    "genDate": "Generated Date",
    "genName": "Generated Name",
    "issueDate": "Receiving Date",
    "issueName": "Received By",
    "approvedDate": "Approved Date",
    "approvedName": "Approved Name",
    "id": "Detail Id",
    "processId": "Process ID",
    "type": "Type",
    "typeOfNote": "Note Type",
    "inspectionRptNo": "Inspection Report No.",
    "acptRejNoteNo": "Acceptance Note No.",
    "acptRejNoteDT": "Acceptance Note Date",
    "dateOfDelivery": "Date of Delivery",
    "ceRegionalCenterCd": "Consignee Regional Center Code",
    "ceRegionalCenterName": "Consignee Regional Center Name",
    "ceAddress": "Consignee Address",
    "ceZipcode": "Consignee Zipcode",
    "crRegionalCenterCd": "Consignor Regional Center Code",
    "crRegionalCenterName": "Consignor Regional Center Name",
    "crAddress": "Consignor Address",
    "crZipcode": "Consignor Zipcode",
    "consumerName": "Consumer Name",
    "supplierName": "Supplier Name",
    "supplierCd": "Supplier Code",
    "address": "Address",
    "contactNo": "Contact No.",
    "note": "Note",
    "noaDate": "NOA Date",
    "noa": "NOA",
    "conditionOfGoods": "Condtion Of Goods",
    "acceptanceNoteNo": "Accept Note No.",
    "returnVoucher": "Return Voucher",
    "challanNo": "Challan No.",
    "supplierCode": "Supplier Code",
    "noteType": "Note Type",
    "demandNoteNo": "Demand Note No.",
    "issueNoteNo": "Issue Note No.",
    "issueNoteDt": "Issue Note Date",
    "interRdDemandNote": "Inter Rd Demand Note",
    // "issueName": "Issue Name",
    "gatePassType": "Gate Pass Type",
    "gatePassDate": "Gate Pass Date",
    "gatePassNo": "Gate Pass No.",
    "noaNo": "NOA No.",
    "modeOfDelivery": "Mode of Delivery",
    "rejectionNoteNo": "Rejection Note No.",
    "termsCondition": "Terms and Condition",
    "dateOfInspection": "Date of Inspection"
}