import React from 'react'
import { consumerDetails, itemDetails, orgConsignorDetails, supplierDetails } from '../commonColumns'
import DetailData from './DetailData'
import { convertEpochToDateString } from '../../../utils/Functions'

const GrnTable = ({type, data, itemList}) => {
    const poExtraColumns = [
        {
            title: "Acceptance Note No.",
            dataIndex: "processId"
        },
        {
            title: "Acceptance Note Date",
            dataIndex: "issueDate"

        },
        {
            title: "Noa No",
            dataIndex: "noa"
        },
        {
            title: "Noa Date",
            dataIndex: "noaDate",
            render: (date) => convertEpochToDateString(date)
        },
        {
            title: "Date of Delivery",
            dataIndex: "dateOfDelivery",
        },
    ]

    const irpExtraColumn = [
        {
            title: "Return Note No.",
            dataIndex: "processId"
        }
    ]
    const dataColumn = [
        {
            title: "GRN Date",
            dataIndex: "grnDate"
        },
        {
            title: "GRN No.",
            dataIndex: "processId"
        },
        {
            title: "Process Type",
            dataIndex: "type"
        },
        {
            title: "Generated By",
            dataIndex: "genName"
        },
        {
            title: "Generation Date",
            dataIndex: "genDate"
        },
        {
            title: "Verified By",
            dataIndex: "issueName"
        },
        {
            title: 'Verification Date',
            dataIndex: "issueDate"
        },
        {
            title: "Terms and Condition",
            dataIndex: "termsCondition"
        },
        {
            title: "Note",
            dataIndex: "note"
        },
        ...orgConsignorDetails,
    ]

    const itemListColumn = [
        ...itemDetails,
        {
            title: "Received Quantity",
            dataIndex: "quantity"
        },
        {
            title: "Budget Head Procurement",
            dataIndex: "budgetHeadProcurement"
        },
        {
            title: "Remarks",
            dataIndex: "remarks"
        },
    ]
  return (
    <DetailData dataColumn={type === "PO" ? [...dataColumn, ...supplierDetails, ...poExtraColumns] :(type === "IRP" ? [...dataColumn, ...consumerDetails, irpExtraColumn] : [] )} itemListColumn={itemListColumn} data={data} itemList={itemList}/>
  )
}

export default GrnTable
